name: Deploy to Fly.io

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.1

    - name: Bundle install
      run: bundle install

    - name: Run RSpec
      run: bundle exec rspec
      env:
        TIME_CARD_PASSWORD: password

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Fly.io CLI
      run: |
        curl -L https://fly.io/install.sh | sh
        echo "/home/runner/.fly/bin" >> $GITHUB_PATH

    - name: Deploy to Fly.io
      run: flyctl deploy
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
