name: Deploy to Fly.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.1

    - name: Bundle install
      run: bundle install

    - name: Install Fly.io CLI
      run: curl -L https://fly.io/install.sh | sh

    - name: Deploy to Fly.io
      run: /usr/local/bin/fly deploy
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}